using UnityEngine;

namespace FriendSlop.Interiors
{
    // Marks a spot inside a room prefab where a piece of furniture can spawn.
    // Anchors are generated by BuildRoomGeometry at edit-time so every room prefab
    // already has a sane set; the runtime spawner picks from them after filtering
    // out anchors that conflict with active doorways.
    public class FurnitureAnchor : MonoBehaviour
    {
        [SerializeField] private AnchorPlacement placement = AnchorPlacement.Wall;
        [Tooltip("Wall the anchor is against. Ignored for Center anchors. Used to skip the " +
                 "anchor if a door spawns on this wall AND the anchor overlaps the door's " +
                 "swing zone.")]
        [SerializeField] private SocketDirection wall = SocketDirection.North;
        [Tooltip("Footprint XZ (metres) reserved for the furniture. Compared against door " +
                 "swing zones to determine if the anchor is blocked.")]
        [SerializeField] private Vector2 footprintXZ = new Vector2(1.5f, 1.5f);

        public AnchorPlacement Placement => placement;
        public SocketDirection Wall      => wall;
        public Vector2 FootprintXZ       => footprintXZ;

        // Bounding-rect on the XZ plane, in room-local coordinates, centred on this anchor.
        public Rect LocalFootprintRect()
        {
            var localPos = transform.localPosition;
            var half = footprintXZ * 0.5f;
            return new Rect(localPos.x - half.x, localPos.z - half.y, footprintXZ.x, footprintXZ.y);
        }

        // Editor-only helpers so the builder can stamp anchor data programmatically.
        public void Configure(AnchorPlacement p, SocketDirection w, Vector2 footprint)
        {
            placement = p;
            wall = w;
            footprintXZ = footprint;
        }

#if UNITY_EDITOR
        private void OnDrawGizmosSelected()
        {
            var col = placement switch
            {
                AnchorPlacement.Wall   => new Color(0.3f, 0.7f, 1f, 0.7f),
                AnchorPlacement.Corner => new Color(1f, 0.6f, 0.2f, 0.7f),
                AnchorPlacement.Center => new Color(0.4f, 1f, 0.4f, 0.7f),
                _                       => Color.white,
            };
            Gizmos.color = col;
            var pos = transform.position;
            Gizmos.DrawSphere(pos, 0.15f);
            Gizmos.DrawWireCube(pos + Vector3.up * 0.5f,
                new Vector3(footprintXZ.x, 1f, footprintXZ.y));
        }
#endif
    }
}
